{
 "title": "Kubernetes",
 "description": "Kubernetes dashboard for Eyeflow environment",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods - NS: $namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"app\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Versão das Imagens - NS: $namespace",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Fase dos PODs por Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=\"$namespace\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Monitoramento - NS: monitoring",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{job=~\"kube-state.+\", namespace=\"monitoring\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Velocidade da Internet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "download_speed", "legendFormat": "Download" },
    { "expr": "upload_speed", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Tempo de PING",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_latency", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Processos Ativos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum(container_processes{kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "Processos"
    }
   ]
  },
  {
   "title": "Ingress Controller Ativo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{job=~\"kube-state.+\", namespace=\"ingress-nginx\"}"
    }
   ]
  },
  { "title": "Kubernetes Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Utilização de Memória",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Utilização de CPU",
   "type": "gauge",
   "description": "Average last minute",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Armazenamento Utilizado",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "PODs em execução",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Mem Utilizada",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU Utilizada",
   "type": "stat",
   "description": "Average last minute",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "description": "Average last minute",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "FS Utilizado",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "FS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Ingress Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Ingress Percentual - Tempo de Resposta e Taxa de Transferência",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kube_service_status_load_balancer_ingress[2m])) by (service))",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"monitor.+\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"monitor.+\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress=~\"monitor.+\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress=~\"monitor.+\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Controller - Requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests [2m])), 0.001)",
     "legendFormat": "ops/s"
    }
   ]
  },
  {
   "title": "Ingress Controller - Média Conexões 2 min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections[2m]))"
    }
   ]
  },
  {
   "title": "Volume - Entrada / Saída",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_request_size_sum[2m]))",
     "legendFormat": "Recebido"
    },
    {
     "expr": "- sum (rate (nginx_ingress_controller_response_size_sum[2m]))",
     "legendFormat": "Transmitido"
    }
   ]
  },
  {
   "title": "Ingress Controller - % Sucesso",
   "type": "stat",
   "description": "Responses not 4xx or 5xx",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{status!~\"[4-5].*\"}[2m])) / sum(irate(nginx_ingress_controller_requests[2m]))"
    }
   ]
  },
  {
   "title": "Recarregamentos com sucesso",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful == 1)"
    }
   ]
  }
 ]
}